### ISSUE TITLE
ReactJS example

### ISSUE THREAD

**Issue by sarendsen** [lume/lume#229]
Can't seem to find an ReactJS example. Anything avaiable?

**Comment by Eskabore** [comment]
Hey. 
I made a Todo-list in ReactJS which code covers all you need to know to start a project : [ReactJS-Todo-List](https://github.com/Eskabore/repo-todo-mzf)
"_A Todo App made built with React. The app include focus management and descriptive attributes in order to improve usability and reduce confusion for both keyboard-only and screenreader users._"

One of the best source to learn about ReactJS and its environment online is [Reactiflux](https://www.reactiflux.com).

https://create-react-app.dev/ details how to quickly start using a ReactJS and provides you a basic template.
"To create a project called my-app, run this command:
```
npx create-react-app my-app
```
"
If you already have NodeJS and npm installed, the code above will provide you with a basic ReactJS template. You will then have to open a preview on your local server to render the code into a new window.

I hope that I have answered your question. If so, please close the issue and give me a star on my [profile](https://github.com/Eskabore) or [repository](https://github.com/Eskabore/repo-todo-mzf).

👍🏾 

Eskabore

**Comment by trusktr** [comment]
Hello! Sorry for the late reply. Codepen supports React JSX, so here's an example of a React component that uses LUME elements on codepen:

https://codepen.io/trusktr/pen/eYgYQaR

**Comment by trusktr** [comment]
Hmmm, apparently that example isn't working in Windows Chrome or Windows Firefox for me. It works great for me in my Linux browsers. Investigating...
