### ISSUE TITLE
The requested module './web.js' contains conflicting star exports for the name

### ISSUE THREAD

**Issue by drclementshimizu** [lume/lume#248]
im gettting some errors when i try to install this:
```
git clone --recursive https://github.com/lume/lume.git


Submodule path 'packages/docsifyjs+docsify': checked out '607ccc6065dc128fd9f07a5251b20e8bbaf535a4'
Submodule path 'packages/element': checked out 'cc54bc4dceadd7b4786207fdd21dcaa2b814dea5'
fatal: remote error: upload-pack: not our ref 8fdbc28a40c40d4f51d7f843bf757b42ff2dd754
Fetched in submodule path 'packages/element-behaviors', but it did not contain 8fdbc28a40c40d4f51d7f843bf757b42ff2dd754. Direct fetching of that commit failed.
```

If i download the project from github then run the install script i get the following error:

```
npm install

ERROR in ./node_modules/@lume/element/dist/index.js 6:0-25
The requested module './web.js' contains conflicting star exports for the name 'untrack' with the previous requested module './variable.js'
```

**Comment by trusktr** [comment]
Thanks! I ran into this problem too. Will publish the update with the fix (for now, it pins Solid.js to <1.5)

**Comment by trusktr** [comment]
I forgot to mention the simple workaround. In package.json, restrict the `solid-js` version to less than 1.5:

```js
"dependencies": {
  "solid-js": ">=1.0.0 <1.5.0"
}
```

Aiming to release an update tomorrow.

**Comment by trusktr** [comment]
A little late on the release, working to get it out.

**Comment by trusktr** [comment]
Update: Almost done with this!

**Comment by trusktr** [comment]
I think this is fixed by now, you should be able to clone the repo no problem, then `npm run fresh` to bootstrap it (install dependencies and link projects together), and finally `npm run examples` to open a browser tab to see some examples.

The build is now not using Webpack, only TypeScript to convert `.ts` to `.js`, and all example `import` Lume using JavaScript module `import` syntax. It should be easier to get up and running with the repo now.

If you are curious to try this again, please let me know if any issues!
